services:
  backend:
    build: ./backend
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/solarwatch
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - API_KEYCITY=b491ad43ba62f535b4ce4a9a96195518
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: solarwatch

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3008:5173"
    depends_on:
      - backend
